### ISSUE TITLE
fails to build with libtesseract 5.1.0

### ISSUE THREAD

**Issue by jonassmedegaard** [elizagamedev/vobsubocr#5]
This project - while preserving the `Cargo.lock`file - fails to build with libtesseract 5.1.0.

The following relatively conservative update to `Cargo.lock` lead to a succesful build for me:
```shell
cargo update --package leptess --package leptonica-plumbing
```

**Comment by elizagamedev** [comment]
Thank you for these--I was neglecting this project, regrettably. I have incorporated your fixes.

**Comment by jonassmedegaard** [comment]
I am quite happy you hadn't abandoned it completely: I find it quite useful.  So useful, in fact, that I am working towards getting it [included officially in Debian](https://bugs.debian.org/1014093).

Thanks a lot!

**Comment by elizagamedev** [comment]
Oh wow, what an honor 😄

**Comment by jonassmedegaard** [comment]
Makes me happy that you see it that way.

From where I stand, *you* are the hero, writing software worthy of worldwide distribution. :-)
