### ISSUE TITLE
Please consider adding release tag

### ISSUE THREAD

**Issue by jonassmedegaard** [elizagamedev/vobsubocr#6]
In my experience this project is functional, and deserves recognition as such.

Please consider adding a release tag.
Perhaps just `v0.0.1` if you are super humble about it, but personally I'd suggest `v0.1.0` to indicate that it not only compiles but also works - to the extend that it has practical use.

**Comment by elizagamedev** [comment]
Done! It's also on crates.io now: https://crates.io/crates/vobsubocr

**Comment by jonassmedegaard** [comment]
Cool!

**Comment by jonassmedegaard** [comment]
Fun fact: Your `README.md` explicitly talks about this project " "not on crates.io yet" - you might wanna rephrase that now ;-)
