### ISSUE TITLE
Can't manage to compile vobsubocr

### ISSUE THREAD

**Issue by afAtedg** [elizagamedev/vobsubocr#7]
Hello,
I can't manage to compile **vobsubocr**.
Here is what I get on terminal :

```
~:/vobsubocr-0.1.0$ cargo install mujmap
    Updating crates.io index
error: failed to download `mujmap v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `~/.cargo/registry/src/github.com-XXXXXXXXXXXXXXXX/mujmap-0.2.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
```

System:
Debian 10 Buster 64 bits

**Comment by jonassmedegaard** [comment]
Sounds like you are using too old version of cargo and/or rustc - probably helps if you share which versiones of those you are using, and how you got them (e.g. did you use rustup or apt or some other approach).

NB! I am not directly involved with this project, only a user like yourself.  Just throwing ideas here that might improve your bug triaging.

**Comment by afAtedg** [comment]
I have installed them with apt.

The versions are :
cargo 0.43.1-3~deb10u1
rustc 1.41.1+dfsg1-1~deb10u1

**Comment by jonassmedegaard** [comment]
Your system - Debian Buster - was [released in 2019](https://en.wikipedia.org/wiki/Debian_version_history#Debian_10_(Buster)) so it should be no surprise that it has no support for Rust edition 2021.

I recommend that you upgrade to Debian Bullseye.

(yes, others recommend that you bypass Debian using rustup but I won't recommend that personally).

**Comment by elizagamedev** [comment]
Thank you @jonassmedegaard for looking into this while I was away. :slightly_smiling_face: 

I will close this since the solution seems to be either upgrading Debian or upgrading rust via rustup.
